### PR TITLE
Fixing minor bugs and typos so that the main runs

### PR DESCRIPTION
**Pull request by jeandut**
There are a few bugs in the code on master:
- the output layer of the LeNet defined in models/vision is of size 1000 instead of 100
- one import is missing in utils: torch.nn.functional as F
- I took the liberty to add some seeding

### CODE REVIEW

**Comment by jeandut** [comment]
Also added a `plt.show` for the ones with funny matplotlib backends.

**Comment by jeandut** [comment]
To have it completely reproducible on GPU one needs to add:
```python
torch.backends.cudnn.deterministic = True  

torch.backends.cudnn.benchmark = False
```
I did not want to add them to the PR for performance issues

**Review by Lyken17 — APPROVED** [review]
Thanks for your PR!

**Comment by jeandut** [comment]
Glad I could help

**Pull request merged**
